# Node
alias = "MyNode"
secret = "ffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffffff"

host = "0.0.0.0"
port = 7070

network = "regtest"

# Wallet
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
db_path = "/tmp/batcher/wallet_from_config.db"

# Broker
[broker_config]
# Initial nodes to connect to (eg. [(pubkey, endpoint)])
bootnodes = [
    ["027f921585f2ac0c7c70e36110adecfd8fd14b8a99bfb3d000a283fcac358fce88", "0.0.0.0:7071"]
]
minimum_fee = 10_000
max_utxo_count = 2

# Bitcoind
[bitcoind_config]
rpc_address = "127.0.0.1:38332"
rpc_user = "bitcoind"
rpc_pass = "bitcoind"
