# Node
alias = "Node-00"
secret = "0000000000000000000000000000000000000000000000000000000000000000"

host = "0.0.0.0"
port = 7070

network = "signet"

peers_db_path = "/tmp/batcher/peers_from_config_0.db"

# Wallet
[wallet]
mnemonic = "letter advice cage absurd amount doctor acoustic avoid letter advice cage above"
file_path = "/tmp/batcher/wallet_from_config_0.db"

# Broker
[broker]
# Initial nodes to connect to (eg. [(pubkey, endpoint)])
bootnodes = []
minimum_fee = 10_000
max_utxo_count = 2
wallet_sync_interval = 60

# Logger
[logger]
file_path = "/tmp/batcher/logger_from_config_0.log"
max_level = "debug"

# Bitcoind
[bitcoind]
rpc_address = "127.0.0.1:38332"
rpc_user = "bitcoind"
rpc_pass = "bitcoind"
