# Node
alias = "Node-01"
secret = "1111111111111111111111111111111111111111111111111111111111111111"

host = "0.0.0.0"
port = 7071

network = "signet"

peers_db_path = "/tmp/batcher/peers_from_config_1.db"

# Wallet
[wallet]
mnemonic = "claim wolf alter poem minor ghost spray fox toy family style group"
file_path = "/tmp/batcher/wallet_from_config_1.db"

# Broker
[broker]
# Initial nodes to connect to (eg. [(pubkey, endpoint)])
bootnodes = [
    ["027f921585f2ac0c7c70e36110adecfd8fd14b8a99bfb3d000a283fcac358fce88", "0.0.0.0:7070"],
]
minimum_fee = 10_000
max_utxo_count = 2
wallet_sync_interval = 60

# Logger
[logger]
file_path = "/tmp/batcher/logger_from_config_1.log"
max_level = "debug"

# Bitcoind
[bitcoind]
rpc_address = "127.0.0.1:38332"
rpc_user = "bitcoind"
rpc_pass = "bitcoind"
